### PR TITLE
Add info about creating the database

### PR DESCRIPTION
**Pull request by mkaszubowski**
I thought it would be helpful to add this info to the docs as many people are looking for the way to create a database.

I would appreciate some input on this, maybe there's something more that should be added or maybe the info is not so helpful after all.

### CODE REVIEW

**Comment by robconery** [comment]
ORMs don't necessarily create a database for you - in fact I know of only one that does (EF) but I'm sure there are others. I'm happy to help describe how to create one, but I don't think we need to give a reason as to why we don't do it (though I have one: Moebius shouldn't have this level of privilege).

**Comment by mkaszubowski** [comment]
@robconery Thanks for the reply. You have a good point. I'm going to edit it soon.
Any input on ways how to create the database (instead of doing it manually or using .sql script)? I'd be glad to add it to the readme.

**Comment by robconery** [comment]
Sure - the easiest way is to use a pg binary:

```
createdb my_db
```

You can also:

```
psql
CREATE DATABASE my_db;
```

**Comment by nurugger07** [comment]
@mkaszubowski how's the edits coming?

**Comment by mkaszubowski** [comment]
Sorry, I didn't have much time recently to edit it. Is it better now? I wasn't sure if I should add the info about the reason Moebius does not create the database, I decided that it's not essential in this paragraph after all. You can let me know what you think.

**Comment by CrowdHailer** [comment]
Hi, 

I think this is worth adding. but would go further. Including why Moebius doesn't create databases is a good idea. I would also like more information on how people recommend running migrations. Even though they are not included.

**Comment by robconery** [comment]
>Including why Moebius doesn't create databases is a good idea

This is going to sound a bit "direct"... but there's no other way to put it: *it's not my job to inform people*, necessarily, about how data access should be done. I like providing information - and maybe there's a way I could offer something in the README.

The primary reason you don't let your ORM create a database for you is permissions. For an ORM to do that for you, you require permissions that go well beyond what a query tool should have. For most users, this typically means "just set the role to SUPER ADMIN" and that's *a really bad idea*.

In addition: Moebius is not intended to be an ORM. It's a query tool and the idea is that the user knows something about PostgreSQL.

I really don't want to be too pointed here; I just don't know how else to put it.

**Comment by CrowdHailer** [comment]
Direct is no problem for me.

I was just reading through all the open pull requests and my comment was an mostly and encouragement to @mkaszubowski to finish his updates if he wanted to. or close the request if not.

**Pull request closed without merging**
