### PR TITLE
FIX: Db.save inside a transaction fails if DocumentQuery.searchable i…

### PR DESCRIPTION
**Pull request by amagdas**
…s used before.

### CODE REVIEW

**Comment by amagdas** [comment]
Fix for #53

**Comment by amagdas** [comment]
So it does fail, will investigate :(

**Comment by amagdas** [comment]
@robconery the root issue is that if the table does not exists before triggering the insert, the mechanism to create it when handling the error is not working inside a transaction is not working as the transaction is already rolledback and in error state.

**Comment by amagdas** [comment]
Not sure why it fails, tests pass fine locally...

**Comment by amagdas** [comment]
@robconery any idea how to fix the tests, locally they pass fine.
Also not sure if the fix is what you expect.

**Comment by xivSolutions** [comment]
@amagdas - just for giggles, try specifying a new document table in your tests, instead of "monkies" (say..."gorillas", or something). I've had problems in the past with the async tests walking on each other when accessing the same table, and "monkies" is used in the document tests file. 

May or may not be the cause, but I too am able to successfully run all tests locally just fine. 

Try changing the doc table to something else, and let's see what happens with Travis...

**Comment by xivSolutions** [comment]
@amagdas  - never mind, that wasn't it. Still failed.

**Comment by xivSolutions** [comment]
I should have noticed earlier that it is a syntax error. Which is odd.

**Comment by amagdas** [comment]
@xivSolutions Yeah, not sure what could trigger it. I've tried as you did/said with a different table name, locally all is good, on travis still fails.

**Pull request closed without merging**
