### PR TITLE
Updates & Test Runner

### PR DESCRIPTION
**Pull request by cpursley**
- Update libraries
- Deprecate [Inflex](https://github.com/nurugger07/inflex) (breaking!)
- Set up code quality & formatting checks
- Add mix tasks to setup test database
- Set up github test runner

### CODE REVIEW

**Comment by robconery** [comment]
Yay for a build! Thanks for setting that up!

**Comment by cpursley** [comment]
@robconery I guess 19th time is the charm...

The main potential breaking change is the removal of the Inflex library. I was having a lot of [difficulty](https://github.com/robconery/moebius/issues/116) getting it to compile reliably. Also, I don't love the opinionated approach about foreign key naming. Plus Inflex is another dependency and not a very complete or maintained one at that (in terms of number English words).

Let me know what you think. Then maybe we could create a new mix release.

**Review by robconery — APPROVED** [review]
Thanks again for this - it looks like many of the changes are due to the syntax style guide, which is fine... I don't have much substantive feedback other than "yay"! If there's something in particular you want my thoughts on - let me know... otherwise... have at it!

**Comment by cpursley** [comment]
You're welcome, thanks for the library.

The main potential breaking change is removal of inflex. How do you feel about that?

I've been chatting with the author of [text](https://hexdocs.pm/text/Text.Inflect.En.html#content) about potentially adding a _singularize_ function. So if you think we should wait and add back that sort of functionality to prevent breaks, let me know.

**Comment by robconery** [comment]
Eh. Let's break things :).

**Comment by cpursley** [comment]
Woot! @robconery do you mind cutting a new hex release for this? Or sharing access with me?

**Pull request merged**
