### PR TITLE
FIX: Db.save inside a transaction fails if DocumentQuery.searchable i…

### LINKED ISSUE #53: Db.save inside a transaction fails if DocumentQuery.searchable is specified before
The following test fails:

``` elixir
test "documents save within a transaction" do
    res = transaction fn(tx) ->
      Moebius.DocumentQuery.db(:monkies) |> Moebius.DocumentQuery.searchable([:name]) |> TestDb.save(%{name: "Mike"}, tx)
    end
    case res do
      {:error, _err} -> flunk "No errors here!"
      res -> assert res
    end
 end
```

### PR DESCRIPTION
**Pull request by amagdas**
…s specified before.
Fixes #53

### CODE REVIEW

**Comment by robconery** [comment]
Rad thanks!

**Comment by robconery** [comment]
Hmm - looks like this broke the build;
https://travis-ci.org/robconery/moebius/builds/130699290

**Comment by amagdas** [comment]
Weird, as the PR tests passed, will investigate.

**Comment by amagdas** [comment]
@robconery can you please trigger a rebuild in Travis for master branch? It looks like a fluke to me.

**Pull request merged**
