### PR TITLE
Source code clean up

### PR DESCRIPTION
**Pull request by milmazz**
This PR include the following improvements:
- Add dogma as a code style linter
- Remove all the trailing whitespace at the end of a line
- Remove all the semicolons to terminate or separate statements
- Promote `~s` instead of escaped double quotes in a string
- Promote that a function chain always begin with a bare value

Please let me know what do you think.

HTH

### CODE REVIEW

**Comment by nurugger07** [comment]
It's up to @robconery but I think think we should probably hold off on this. The code base is still changing rapidly and even several of these files are being reworked at the moment. I appreciate the contribution though!

**Comment by robconery** [comment]
Yes - thank you so much @milmazz but we're not at this place yet. Appreciate your input!

**Comment by milmazz** [comment]
@robconery @nurugger07 No problem, but at least consider remove the semicolons to terminate some statements in some tests (it's really weird).

BTW, really nice project!

**Comment by robconery** [comment]
Absolutely - we're literally at the "what will stick to the wall" phase. I litter our Slack channel with crazy ass ideas and crappy code, @nurugger07 cleans it up and adds some of his awesome - so this is still really Wild West to use an American term :).

I _really_ do appreciate your help, we will **absolutely** need it. Just not yet - it would be obsolete in a few hours!

**Pull request closed without merging**
